name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3   
    - uses: actions/setup-node@v3
      with:
        node-version: '16'    
        cache: 'npm'
    - run: npm ci
    - run: npm test
    
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
