name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test   


      - name: Set output
        id: vars_output
        run: >-
          echo git_hash=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_ENV
          echo git_branch=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV    
          docker build . --file Dockerfile --tag virtlet:${git_hash} 
      
      - name: Check output
        env:
          TAG_VERSION:  ${{ steps.vars_output.outputs.git_hash}}
          BRANCH:       ${{ steps.vars_output.outputs.git_branch}}
        run: >-
          echo $git_hash
          echo $(git_hash)
          echo $TAG_VERSION
          echo $(TAG_VERSION)
          echo ${{ env.TAG_VERSION}}
          echo $(TAG_VERSION)
          echo ${{ steps.vars_output.outputs.git_hash }}
          echo ${{ steps.vars_output.outputs.git_branch }}

#          echo ${ TAG_VERSION }

      - name: Build the Docker image
        env: 
          DOCKER_TAG: "7"           
          TAG_VERSION:  ${{ steps.vars_output.outputs.git_hash}}
          #! DOCKER_USER: ${{ secrets.DOCKER_USER }}
          #! DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          #! DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: "love7310"  #"love7310@naver.com"
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_PASSWORD: "rlawnsdud#08"
        run: >-          
          echo "docker_tag=work-11" >> $GITHUB_ENV \
          echo "tag=${{ steps.vars_output.outputs.git_hash}}" >> $GITHUB_ENV
          docker build . --file Dockerfile --tag virtlet:${{ env.tag }} \
          


#          docker build . --file Dockerfile --tag virtlet:${DOCKER_TAG} \
#          docker build . --file Dockerfile --tag virtlet:${{ env.TAG_VERSION}} \          

          

      - name: Login to Docker Hub
        run: echo The username ${DOCKER_USER}
      - name: Login to Docker password
        run: echo  $DOCKER_PASSWORD
      - name: Login to Docker user
        run: echo  $DOCKER_USER
      - name: Login to Docker password2
        run: echo $DOCKER_PASSWORD
      - name: env.DockerUser
        run: echo ${{ env.DOCKER_USER }}

#          echo "{docker_tag}=${(date +%s)}" >> $GITHUB_ENV \ 
# ${{ steps.vars.outputs.tag }} 
#          echo "{environment_variable_name}={value}" >> $GITHUB_ENV
#          echo "{}={}"  
#          echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY



#!       -
#!         name: Login to Docker Hub
#!         uses: docker/login-action@v2
#!         with:
#! #          username: ${{ secrets.DOCKERHUB_USERNAME }}
#! #          password: ${{ secrets.DOCKERHUB_TOKEN }}
#!           username: "love7310@naver.com" # ${ DOCKER_USER }
#!           password: "dckr_pat_vBAeozyHjqkHF4hRVA-R6FSH3gA" #"rlawnsdud#08" # ${ DOCKER_PASSWORD }


#!       -
#!         name: Build and push
#!         uses: docker/build-push-action@v3
#!         with:
#!           push: true
#! #          tags: love7310/virtlet:${{ steps.meta.outputs.tags }}
#!           tags: love7310/virtlet:${DOCKER_TAG}





      #! - name: Set the value
      #!   id: step_one
      #!   run: |
      #!     echo "action_state=yellow" >> $GITHUB_ENV

      #! - name: Use the value
      #!   id: step_two
      #!   env: 
      #!     DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      #!   run: |
      #!     echo "${{ env.action_state }}" # This will output 'yellow'

      #! - name: Login to Docker Hub
      #!   run: echo The username is ${{ inputs.username }}
      #! - run: echo secret- ${{ secrets.DOCKERHUB_USERNAME }}
      #! - run: echo secret2- {$DOCKERHUB_USERNAME }}
      #! - run: echo dockertag ${{env.docker_tag}} 
      #! - run: echo dockertag2 ${{env.docker_tag2}} 
      #! - run: echo tag ${{ steps.vars.outputs.tags }}
      #! - run: echo tag-label ${{ steps.vars.outputs.tags }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: "love7310" #${{ env.DOCKER_USER }}
          #password: ${{ secrets.DOCKER_PASSWORD }}
          #username: $DOCKER_USER  # "love7310"    x:  ${{ DOCKER_USER }}  x: ${DOCKER_USER} x: $DOCKER_USER
          password: "rlawnsdud#08"
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: love7310/virtlet
      
      - name: Build and push Docker image
        env:
          TAG_VERSION:  ${{ steps.vars_output.outputs.git_hash}}
          BRANCH:       ${{ steps.vars_output.outputs.git_branch}}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.vars_output.outputs.git_hash }}
          #tags: $TAG_VERSION
          labels: ${{ steps.meta.outputs.labels }}        

      


# jobs:
# #  my_job:
# #    name: deploy to staging
#   runs-on: ubuntu-18.04

#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v3   
#     - uses: actions/setup-node@v3
#       with:
#         node-version: '16'    
#         cache: 'npm'
#     - run: npm ci
#     - run: npm test
    
#     - name: npm install, build and test
#       run: |
#         npm install
#         npm run build --if-present
#         npm test
    
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
