name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test   

      - name: variable test
        id : var_test
        env:
          docker_tag: "7"
        run: >-
          echo "::set-output name=set_innser_docker_tag::inner-data"
          echo "::set-output name=set_echo_docker_tag::$(echo ${docker_tag})"                  

          
#          echo ${{ env.docker_tag }}  # FAIL 7
#          echo "::set-output name=set_docker_tag::${docker_tag}"  안됨



#          ## env 에다 변수를 넣어야 하나.
#          echo $docker_tag  # OK 7          
        
      - name: get_output
        run: >-
          echo ${{ steps.var_test.outputs.set_docker_tag }}
          

      - name: get_output2
        run: echo ${{ steps.var_test.outputs.set_echo_docker_tag }}          
      
      - name: get_output3
        run: echo ${{ steps.var_test.outputs.set_innser_docker_tag }}          

      - name: get_output4
        run: echo json(${{ steps.var_test.outputs }})


      - id: set-foo
        run: echo "::set-output name=foo::bar"
      - run: echo ${{ steps.set-foo.outputs.foo }}        